"""db defined

Revision ID: 2a451727e6a1
Revises: f414cc5c4245
Create Date: 2024-03-04 18:16:58.665030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a451727e6a1'
down_revision = 'f414cc5c4245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pancard_no', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('pincode', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('creation_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('account_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('mob_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index('ix_account_timestamp')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.create_index('ix_account_timestamp', ['timestamp'], unique=False)
        batch_op.alter_column('mob_no',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('account_no',
               existing_type=sa.String(length=12),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('creation_time')
        batch_op.drop_column('pincode')
        batch_op.drop_column('pancard_no')

    # ### end Alembic commands ###
