"""account table

Revision ID: f414cc5c4245
Revises: e62927b8c835
Create Date: 2024-03-04 01:31:57.912976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f414cc5c4245'
down_revision = 'e62927b8c835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_no', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('mob_no', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('account_no')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_username'))
        batch_op.drop_index(batch_op.f('ix_account_timestamp'))

    op.drop_table('account')
    # ### end Alembic commands ###
